name: Deploy and Run Flask Web Application on EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: List directory contents
        run: |
          ls -R

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          cd web_page  # Переход в директорию с Dockerfile и кодом приложения
          docker build -t ${{ secrets.DOCKER_USERNAME }}/guessing-game-flask-app:latest -f Dockerfile .

      # Отправка собранного Docker-образа в Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/guessing-game-flask-app:latest

      # Развертывание приложения на сервере EC2 с помощью SSH
      - name: Deploy to EC2 with SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Удаление существующего контейнера, если он есть
            sudo docker container rm -f guessing-game-flask-app || true
            # Загрузка последней версии Docker-образа
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/guessing-game-flask-app:latest
            # Запуск нового контейнера с приложением
            sudo docker run -d --name guessing-game-flask-app -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/guessing-game-flask-app:latest
            # Проверка состояния запущенных контейнеров
            sudo docker ps

